@startuml

:Usuario:
:Administrador:

(Iniciar sesión)
(Recuperar contraseña)
(Modificar contraseña)
(Cerrar sesión)
(Registrar usuario)
(Instalar programa)

:Usuario: -- (Iniciar sesión)
:Usuario: -- (Recuperar contraseña)
:Usuario: -- (Modificar contraseña)
:Usuario: -- (Cerrar sesión)

:Administrador: -- (Registrar usuario)
:Administrador: -- (Instalar programa)

:Usuario: <|-- :Administrador:




@enduml