@startuml

:Cliente:

(Meter dinero)
(Pedir azúcar)
(Pedir producto)
(Cancelar)
(Devolver dinero)

:Cliente: -- (Meter dinero)
:Cliente: -- (Pedir azúcar)
:Cliente: -- (Pedir producto)
:Cliente: -- (Cancelar)

(Cancelar) ..> (Devolver dinero) : <<include>>
(Pedir producto) ..> (Devolver dinero) : <<include>>


@enduml