@startuml

:new Actor:

(Identificarse)
(Pagar)
(Elegir mensajero)
(Confirmar)
(Registrarse)
(Pagar con tarjeta)
(Pagar con trasferencia)

:new Actor: -- (Identificarse)
:new Actor: -- (Pagar)
:new Actor: -- (Elegir mensajero)
:new Actor: -- (Confirmar)

(Identificarse) <.. (Registrarse) : <<extend>>
(Pagar) <|-- (Pagar con tarjeta)
(Pagar) <|-- (Pagar con trasferencia)


@enduml